# Forward propagation

In [1]:
import torch

torch.manual_seed(1); # for the reproducibility

## Linear model

In [2]:
X = torch.tensor([[-8.0, 1.0, -3.0, 5.0, 2.0], [-2.0, 2.0, -1.0, 5.0, 2.0], [7.0, 1.0, 9.0, -5.0, -2.0]])
X

tensor([[-8.,  1., -3.,  5.,  2.],
        [-2.,  2., -1.,  5.,  2.],
        [ 7.,  1.,  9., -5., -2.]])

In [3]:
X.shape

torch.Size([3, 5])

In [4]:
W = torch.rand(5).view(1, 5)  # random numbers from (0, 1)
b = torch.rand(1)

In [5]:
W

tensor([[0.7576, 0.2793, 0.4031, 0.7347, 0.0293]])

In [6]:
b

tensor([0.7999])

In [7]:
W.shape, b.shape

(torch.Size([1, 5]), torch.Size([1]))

$$ \boldsymbol z =  X\, {\color{blue}W}^T \oplus {\color{blue} b} \in 
\mathbb R^{{\color{magenta}N}\times 1}  $$

In [8]:
z = torch.mm( X, W.T ) + b
z.shape

torch.Size([3, 1])

In [9]:
z

tensor([[-2.4591],
        [ 3.1721],
        [ 6.2782]])

$$ \boldsymbol a = {\color{red} \sigma}(\boldsymbol z) \in 
\mathbb R^{{\color{magenta}N}\times 1}  $$

In [10]:
a = torch.sigmoid(z)
a

tensor([[0.0788],
        [0.9598],
        [0.9981]])